import { lazy } from 'react';
import { AppDefinition, AppCategory } from '../types/app.types';

export const APP_REGISTRY: AppDefinition[] = [
  {
    id: 'about',
    name: 'About Me',
    icon: 'user',
    description: 'Learn more about me and my background',
    category: AppCategory.PORTFOLIO,
    component: lazy(() => import('../apps/AboutApp')),
    defaultWindowSize: { width: 700, height: 500 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'blue',
  },
  {
    id: 'skills',
    name: 'Skills & Technologies',
    icon: 'code',
    description: 'Overview of my technical skills',
    category: AppCategory.PORTFOLIO,
    component: lazy(() => import('../apps/SkillsApp')),
    defaultWindowSize: { width: 800, height: 600 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'purple',
  },
  {
    id: 'education',
    name: 'Education',
    icon: 'graduation-cap',
    description: 'My academic journey',
    category: AppCategory.PORTFOLIO,
    component: lazy(() => import('../apps/EducationApp')),
    defaultWindowSize: { width: 650, height: 500 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'green',
  },
  {
    id: 'projects',
    name: 'Projects',
    icon: 'folder-code',
    description: 'Showcase of my projects',
    category: AppCategory.PORTFOLIO,
    component: lazy(() => import('../apps/ProjectsApp')),
    defaultWindowSize: { width: 900, height: 650 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'orange',
  },
  {
    id: 'certifications',
    name: 'Certifications',
    icon: 'award',
    description: 'My professional certifications',
    category: AppCategory.PORTFOLIO,
    component: lazy(() => import('../apps/CertificationsApp')),
    defaultWindowSize: { width: 700, height: 500 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'yellow',
  },
  {
    id: 'experience',
    name: 'Experience',
    icon: 'briefcase',
    description: 'My work experience',
    category: AppCategory.PORTFOLIO,
    component: lazy(() => import('../apps/ExperienceApp')),
    defaultWindowSize: { width: 750, height: 550 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'red',
  },
  {
    id: 'contact',
    name: 'Contact Me',
    icon: 'mail',
    description: 'Get in touch with me',
    category: AppCategory.PORTFOLIO,
    component: lazy(() => import('../apps/ContactApp')),
    defaultWindowSize: { width: 500, height: 600 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'teal',
  },
  {
    id: 'resume',
    name: 'Resume Viewer',
    icon: 'file-text',
    description: 'View and download my resume',
    category: AppCategory.PORTFOLIO,
    component: lazy(() => import('../apps/ResumeApp')),
    defaultWindowSize: { width: 800, height: 700 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'indigo',
  },
  {
    id: 'terminal',
    name: 'Terminal',
    icon: 'terminal',
    description: 'Command line interface',
    category: AppCategory.SYSTEM,
    component: lazy(() => import('../apps/TerminalApp')),
    defaultWindowSize: { width: 700, height: 450 },
    supportsMobile: false,
    supportsDesktop: true,
    singleton: false,
    shortcut: 'Ctrl+T',
    accentColor: 'green',
  },
  {
    id: 'settings',
    name: 'System Settings',
    icon: 'settings',
    description: 'Configure system options',
    category: AppCategory.SYSTEM,
    component: lazy(() => import('../apps/SettingsApp')),
    defaultWindowSize: { width: 750, height: 550 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    shortcut: 'Ctrl+Shift+S',
    accentColor: 'gray',
  },
  {
    id: 'file-explorer',
    name: 'File Explorer',
    icon: 'folder',
    description: 'Browse files and folders',
    category: AppCategory.SYSTEM,
    component: lazy(() => import('../apps/FileExplorerApp')),
    defaultWindowSize: { width: 800, height: 500 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: false,
    shortcut: 'Ctrl+E',
    accentColor: 'yellow',
  },
  {
    id: 'gallery',
    name: 'Gallery',
    icon: 'image',
    description: 'Image viewer',
    category: AppCategory.UTILITY,
    component: lazy(() => import('../apps/GalleryApp')),
    defaultWindowSize: { width: 850, height: 600 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: false,
    accentColor: 'pink',
  },
  {
    id: 'browser',
    name: 'Mini Browser',
    icon: 'globe',
    description: 'Web browser',
    category: AppCategory.UTILITY,
    component: lazy(() => import('../apps/BrowserApp')),
    defaultWindowSize: { width: 900, height: 650 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: false,
    accentColor: 'blue',
  },
];
