import { type AppDefinition, AppCategory } from '../types/app.types';
import AboutApp from '../apps/AboutApp';
import SkillsApp from '../apps/SkillsApp';
import EducationApp from '../apps/EducationApp';
import ProjectsApp from '../apps/ProjectsApp';
import CertificationsApp from '../apps/CertificationsApp';
import ExperienceApp from '../apps/ExperienceApp';
import ContactApp from '../apps/ContactApp';
import ResumeApp from '../apps/ResumeApp';
import TerminalApp from '../apps/TerminalApp';
import SettingsApp from '../apps/SettingsApp';
import FileExplorerApp from '../apps/FileExplorerApp';
import GalleryApp from '../apps/GalleryApp';
import BrowserApp from '../apps/BrowserApp';

export const APP_REGISTRY: AppDefinition[] = [
  {
    id: 'about',
    name: 'About Me',
    icon: 'user',
    description: 'Learn more about me and my background',
    category: AppCategory.PORTFOLIO,
    component: AboutApp,
    defaultWindowSize: { width: 700, height: 500 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'blue',
  },
  {
    id: 'skills',
    name: 'Skills & Technologies',
    icon: 'code',
    description: 'Overview of my technical skills',
    category: AppCategory.PORTFOLIO,
    component: SkillsApp,
    defaultWindowSize: { width: 800, height: 600 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'purple',
  },
  {
    id: 'education',
    name: 'Education',
    icon: 'graduation-cap',
    description: 'My academic journey',
    category: AppCategory.PORTFOLIO,
    component: EducationApp,
    defaultWindowSize: { width: 650, height: 500 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'green',
  },
  {
    id: 'projects',
    name: 'Projects',
    icon: 'folder-code',
    description: 'Showcase of my projects',
    category: AppCategory.PORTFOLIO,
    component: ProjectsApp,
    defaultWindowSize: { width: 900, height: 650 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'orange',
  },
  {
    id: 'certifications',
    name: 'Certifications',
    icon: 'award',
    description: 'My professional certifications',
    category: AppCategory.PORTFOLIO,
    component: CertificationsApp,
    defaultWindowSize: { width: 700, height: 500 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'yellow',
  },
  {
    id: 'experience',
    name: 'Experience',
    icon: 'briefcase',
    description: 'My work experience',
    category: AppCategory.PORTFOLIO,
    component: ExperienceApp,
    defaultWindowSize: { width: 750, height: 550 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'red',
  },
  {
    id: 'contact',
    name: 'Contact Me',
    icon: 'mail',
    description: 'Get in touch with me',
    category: AppCategory.PORTFOLIO,
    component: ContactApp,
    defaultWindowSize: { width: 500, height: 600 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'teal',
  },
  {
    id: 'resume',
    name: 'Resume Viewer',
    icon: 'file-text',
    description: 'View and download my resume',
    category: AppCategory.PORTFOLIO,
    component: ResumeApp,
    defaultWindowSize: { width: 800, height: 700 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    accentColor: 'indigo',
  },
  {
    id: 'terminal',
    name: 'Terminal',
    icon: 'terminal',
    description: 'Command line interface',
    category: AppCategory.SYSTEM,
    component: TerminalApp,
    defaultWindowSize: { width: 700, height: 450 },
    supportsMobile: false,
    supportsDesktop: true,
    singleton: false,
    shortcut: 'Ctrl+T',
    accentColor: 'green',
  },
  {
    id: 'settings',
    name: 'System Settings',
    icon: 'settings',
    description: 'Configure system options',
    category: AppCategory.SYSTEM,
    component: SettingsApp,
    defaultWindowSize: { width: 750, height: 550 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: true,
    shortcut: 'Ctrl+Shift+S',
    accentColor: 'gray',
  },
  {
    id: 'file-explorer',
    name: 'File Explorer',
    icon: 'folder',
    description: 'Browse files and folders',
    category: AppCategory.SYSTEM,
    component: FileExplorerApp,
    defaultWindowSize: { width: 800, height: 500 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: false,
    shortcut: 'Ctrl+E',
    accentColor: 'yellow',
  },
  {
    id: 'gallery',
    name: 'Gallery',
    icon: 'image',
    description: 'Image viewer',
    category: AppCategory.UTILITY,
    component: GalleryApp,
    defaultWindowSize: { width: 850, height: 600 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: false,
    accentColor: 'pink',
  },
  {
    id: 'browser',
    name: 'Mini Browser',
    icon: 'globe',
    description: 'Web browser',
    category: AppCategory.UTILITY,
    component: BrowserApp,
    defaultWindowSize: { width: 900, height: 650 },
    supportsMobile: true,
    supportsDesktop: true,
    singleton: false,
    accentColor: 'blue',
  },
];
