import { type KeyboardShortcut } from '../types/input.types';

export const KEYBOARD_SHORTCUTS: KeyboardShortcut[] = [
  {
    id: 'toggle-start-menu',
    keys: ['Control', ' '],
    description: 'Open Start Menu / App Launcher',
    action: 'TOGGLE_START_MENU',
    scope: 'global',
    enabled: true,
  },
  {
    id: 'switch-window',
    keys: ['Alt', 'Tab'],
    description: 'Switch between open windows',
    action: 'SWITCH_WINDOW',
    scope: 'global',
    enabled: true,
  },
  {
    id: 'open-terminal',
    keys: ['Control', 't'],
    description: 'Open Terminal',
    action: 'OPEN_TERMINAL',
    scope: 'global',
    enabled: true,
  },
  {
    id: 'open-explorer',
    keys: ['Control', 'e'],
    description: 'Open File Explorer',
    action: 'OPEN_EXPLORER',
    scope: 'global',
    enabled: true,
  },
  {
    id: 'toggle-desktop',
    keys: ['Control', 'd'],
    description: 'Show/Hide Desktop (minimize all)',
    action: 'TOGGLE_DESKTOP',
    scope: 'global',
    enabled: true,
  },
  {
    id: 'lock-screen',
    keys: ['Control', 'l'],
    description: 'Lock Screen',
    action: 'LOCK_SCREEN',
    scope: 'global',
    enabled: true,
  },
  {
    id: 'open-settings',
    keys: ['Control', 'Shift', 's'],
    description: 'Open Settings',
    action: 'OPEN_SETTINGS',
    scope: 'global',
    enabled: true,
  },
  {
    id: 'close-window',
    keys: ['Control', 'w'],
    description: 'Close active window',
    action: 'CLOSE_WINDOW',
    scope: 'global',
    enabled: true,
  },
  {
    id: 'toggle-fullscreen',
    keys: ['F11'],
    description: 'Toggle fullscreen for active window',
    action: 'TOGGLE_FULLSCREEN',
    scope: 'global',
    enabled: true,
  },
  {
    id: 'snap-left',
    keys: ['Control', 'ArrowLeft'],
    description: 'Snap window left',
    action: 'SNAP_WINDOW_LEFT',
    scope: 'global',
    enabled: true,
  },
  {
    id: 'snap-right',
    keys: ['Control', 'ArrowRight'],
    description: 'Snap window right',
    action: 'SNAP_WINDOW_RIGHT',
    scope: 'global',
    enabled: true,
  },
  {
    id: 'escape',
    keys: ['Escape'],
    description: 'Close active modal or menu',
    action: 'ESCAPE',
    scope: 'global',
    enabled: true,
  },
  // Taskbar shortcuts 1-9
  ...Array.from({ length: 9 }, (_, i) => ({
    id: `open-app-${i + 1}`,
    keys: ['Control', String(i + 1)],
    description: `Open app in position ${i + 1}`,
    action: `OPEN_APP_${i + 1}`,
    scope: 'global' as const,
    enabled: true,
  })),
];
